# 1. Create a 3x3x3 array with random values 

In [2]:
import numpy as np
random = np.random.random([3,3,3])

In [3]:
random

array([[[0.46797308, 0.99616266, 0.43868115],
        [0.39436174, 0.57624746, 0.91645071],
        [0.10788817, 0.55184367, 0.22566958]],

       [[0.24179324, 0.11094797, 0.20171061],
        [0.95307848, 0.37081977, 0.84498608],
        [0.42700431, 0.51949485, 0.24035963]],

       [[0.29451671, 0.52682557, 0.50438909],
        [0.00375546, 0.70223871, 0.21808418],
        [0.73397286, 0.90343871, 0.21475154]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [18]:
diagnoal = np.diag([1,2,3,4,4-4])

In [19]:
diagnoal

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 0]])

In [20]:
diagnoal.shape

(5, 5)

# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [23]:
a = np.zeros([8,8])
a[1::2,::2]=1
a[::2,1::2]=1
a

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

# 4. Normalize a 5x5 random matrix

In [26]:
ran = np.random.random([5,5])
x = ran/np.linalg.norm(ran)
x

array([[0.31780833, 0.01553407, 0.02414649, 0.18814863, 0.20989756],
       [0.354063  , 0.18832599, 0.16507669, 0.06195749, 0.0029847 ],
       [0.05961836, 0.0950016 , 0.26622464, 0.26677858, 0.02510495],
       [0.16754827, 0.37329173, 0.01620135, 0.25069945, 0.14485849],
       [0.26600195, 0.31697521, 0.16864266, 0.05061089, 0.1333684 ]])

# 5.  How to find common values between two arrays?

In [27]:
a = np.array([1,2,3,4,5,6,7])
b = np.array([1,7,8,9,10,11])
com_value = np.intersect1d(a,b)
com_value

array([1, 7])

# 6.How to get the dates of yesterday, today and tomorrow?

In [36]:
yesterday = np.datetime64('today','D')-np.timedelta64(1,'D')
print("Yesterday\n",yesterday)
today = np.datetime64('today','D')
print("Today\n",today)
tomorrow = np.datetime64('today','D')+np.timedelta64(1,'D')
print("Yesterday\n",tomorrow)

Yesterday
 2020-07-25
Today
 2020-07-26
Yesterday
 2020-07-27


# 7. Consider two random array A and B, check if they are equal

In [47]:
a = np.random.randint(0,20,10)
print("Array A:",a)
b = np.random.randint(0,20,10)
print("Array B:",b)
equal = np.array_equal(a,b)
print("Array Values are equal=",equal)

Array A: [16  1 10 13  4 15  5  0 15  7]
Array B: [19 12 16 14  0  2  6 13  3 14]
Array Values are equal= False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [54]:
a = np.random.random(10)
print("Random Array:\n",a)
a[a.argmax()]=0
print("After replace values:\n",a)


Random Array:
 [0.08540457 0.2497113  0.91178586 0.79870521 0.1381508  0.48127229
 0.61506697 0.99141859 0.57394095 0.32626861]
After replace values:
 [0.08540457 0.2497113  0.91178586 0.79870521 0.1381508  0.48127229
 0.61506697 0.         0.57394095 0.32626861]


# 9. How to print all the values of an array?

In [55]:
output = np.arange(100)
print(output)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


# 10.Subtract the mean of each row of a matrix

In [62]:
a = np.random.randint(0,100,10).reshape([2,5])
print("Matrix:\n",a)
b = a-a.mean(axis=1,keepdims=True)
print("Subtract the mean values:\n",b)

Matrix:
 [[25 49 60 68 19]
 [29 44 81  2 57]]
Subtract the mean values:
 [[-19.2   4.8  15.8  23.8 -25.2]
 [-13.6   1.4  38.4 -40.6  14.4]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [63]:
a = np.ones(5)
print("Vectors:",a)
b = np.random.randint(0,len(a),10)
print("Index Vector:",b)
a += np.bincount(b, minlength=len(a))
print("After vector",a)

Vectors: [1. 1. 1. 1. 1.]
Index Vector: [1 2 3 4 0 0 3 3 4 0]
After vector [4. 2. 2. 4. 3.]


# 12.How to get the diagonal of a dot product?

In [67]:
a = np.arange(9).reshape(3,3)
print(a)
b = np.arange(9).reshape(3,3)
print(b)

diag = np.diag(a.dot(b))
print(diag)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[ 15  54 111]


# 13.How to find the most frequent value in an array?

In [69]:
a = np.random.randint(0,10,20)
print("Arrat:\n",a)
print("Most frequent values:\n",np.bincount(a).argmax())

Arrat:
 [3 7 3 8 8 4 8 1 1 7 9 0 5 7 0 7 6 9 0 8]
Most frequent values:
 7


# 14.How to get the n largest values of an array

In [72]:
a = np.array([1,2,100,120,130,5,6,7,8,210])
print(a)
n = 1
b = a[np.argsort(a)[-n:]]
print("largest values of array values:",b)

[  1   2 100 120 130   5   6   7   8 210]
largest values of array values: [210]


# 15.How to create a record array from a regular array?

In [73]:
a = np.array(['Cricket','Football','Kabadi'])
b = np.array(['karnataga','kerala','Tamilnadu'])
c = np.array([3,2,1])
records = np.core.records.fromarrays([a,b,c])
print(records[0])
print(records[1])
print(records[2])

('Cricket', 'karnataga', 3)
('Football', 'kerala', 2)
('Kabadi', 'Tamilnadu', 1)
